/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as MuuzajiRouteImport } from './routes/muuzaji'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminMauzoRouteImport } from './routes/admin.mauzo'
import { Route as AdminRipotiRouteImport } from './routes/admin.ripoti'
import { Route as AdminZaidiRouteImport } from './routes/admin.zaidi'
import { Route as MuuzajiIndexRouteImport } from './routes/muuzaji.index'
import { Route as MuuzajiMauzoRouteImport } from './routes/muuzaji.mauzo'
import { Route as MuuzajiMipangilioRouteImport } from './routes/muuzaji.mipangilio'
import { Route as AdminBidhaaIndexRouteImport } from './routes/admin.bidhaa.index'
import { Route as AdminBidhaaIdRouteImport } from './routes/admin.bidhaa.$id'
import { Route as AdminBidhaaOngezaRouteImport } from './routes/admin.bidhaa.ongeza'
import { Route as AdminZaidiBajetiRouteImport } from './routes/admin.zaidi.bajeti'
import { Route as AdminZaidiMatumiziRouteImport } from './routes/admin.zaidi.matumizi'
import { Route as AdminZaidiStoreRouteImport } from './routes/admin.zaidi.store'
import { Route as AdminZaidiWakalaRouteImport } from './routes/admin.zaidi.wakala'
import { Route as AdminZaidiWatumiajiRouteImport } from './routes/admin.zaidi.watumiaji'
import { Route as AdminBidhaaIdHaririRouteImport } from './routes/admin.bidhaa.$id.Hariri'
import { Route as AdminBidhaaIdOngezaRouteImport } from './routes/admin.bidhaa.$id.Ongeza'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const MuuzajiRoute = MuuzajiRouteImport.update({
  id: '/muuzaji',
  path: '/muuzaji',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMauzoRoute = AdminMauzoRouteImport.update({
  id: '/mauzo',
  path: '/mauzo',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRipotiRoute = AdminRipotiRouteImport.update({
  id: '/ripoti',
  path: '/ripoti',
  getParentRoute: () => AdminRoute,
} as any)
const AdminZaidiRoute = AdminZaidiRouteImport.update({
  id: '/zaidi',
  path: '/zaidi',
  getParentRoute: () => AdminRoute,
} as any)
const MuuzajiIndexRoute = MuuzajiIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MuuzajiRoute,
} as any)
const MuuzajiMauzoRoute = MuuzajiMauzoRouteImport.update({
  id: '/mauzo',
  path: '/mauzo',
  getParentRoute: () => MuuzajiRoute,
} as any)
const MuuzajiMipangilioRoute = MuuzajiMipangilioRouteImport.update({
  id: '/mipangilio',
  path: '/mipangilio',
  getParentRoute: () => MuuzajiRoute,
} as any)
const AdminBidhaaIndexRoute = AdminBidhaaIndexRouteImport.update({
  id: '/bidhaa/',
  path: '/bidhaa/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBidhaaIdRoute = AdminBidhaaIdRouteImport.update({
  id: '/bidhaa/$id',
  path: '/bidhaa/$id',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBidhaaOngezaRoute = AdminBidhaaOngezaRouteImport.update({
  id: '/bidhaa/ongeza',
  path: '/bidhaa/ongeza',
  getParentRoute: () => AdminRoute,
} as any)
const AdminZaidiBajetiRoute = AdminZaidiBajetiRouteImport.update({
  id: '/bajeti',
  path: '/bajeti',
  getParentRoute: () => AdminZaidiRoute,
} as any)
const AdminZaidiMatumiziRoute = AdminZaidiMatumiziRouteImport.update({
  id: '/matumizi',
  path: '/matumizi',
  getParentRoute: () => AdminZaidiRoute,
} as any)
const AdminZaidiStoreRoute = AdminZaidiStoreRouteImport.update({
  id: '/store',
  path: '/store',
  getParentRoute: () => AdminZaidiRoute,
} as any)
const AdminZaidiWakalaRoute = AdminZaidiWakalaRouteImport.update({
  id: '/wakala',
  path: '/wakala',
  getParentRoute: () => AdminZaidiRoute,
} as any)
const AdminZaidiWatumiajiRoute = AdminZaidiWatumiajiRouteImport.update({
  id: '/watumiaji',
  path: '/watumiaji',
  getParentRoute: () => AdminZaidiRoute,
} as any)
const AdminBidhaaIdHaririRoute = AdminBidhaaIdHaririRouteImport.update({
  id: '/Hariri',
  path: '/Hariri',
  getParentRoute: () => AdminBidhaaIdRoute,
} as any)
const AdminBidhaaIdOngezaRoute = AdminBidhaaIdOngezaRouteImport.update({
  id: '/Ongeza',
  path: '/Ongeza',
  getParentRoute: () => AdminBidhaaIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/muuzaji': typeof MuuzajiRouteWithChildren
  '/admin/mauzo': typeof AdminMauzoRoute
  '/admin/ripoti': typeof AdminRipotiRoute
  '/admin/zaidi': typeof AdminZaidiRouteWithChildren
  '/muuzaji/mauzo': typeof MuuzajiMauzoRoute
  '/muuzaji/mipangilio': typeof MuuzajiMipangilioRoute
  '/admin/': typeof AdminIndexRoute
  '/muuzaji/': typeof MuuzajiIndexRoute
  '/admin/bidhaa/$id': typeof AdminBidhaaIdRouteWithChildren
  '/admin/bidhaa/ongeza': typeof AdminBidhaaOngezaRoute
  '/admin/zaidi/bajeti': typeof AdminZaidiBajetiRoute
  '/admin/zaidi/matumizi': typeof AdminZaidiMatumiziRoute
  '/admin/zaidi/store': typeof AdminZaidiStoreRoute
  '/admin/zaidi/wakala': typeof AdminZaidiWakalaRoute
  '/admin/zaidi/watumiaji': typeof AdminZaidiWatumiajiRoute
  '/admin/bidhaa/': typeof AdminBidhaaIndexRoute
  '/admin/bidhaa/$id/Hariri': typeof AdminBidhaaIdHaririRoute
  '/admin/bidhaa/$id/Ongeza': typeof AdminBidhaaIdOngezaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin/mauzo': typeof AdminMauzoRoute
  '/admin/ripoti': typeof AdminRipotiRoute
  '/admin/zaidi': typeof AdminZaidiRouteWithChildren
  '/muuzaji/mauzo': typeof MuuzajiMauzoRoute
  '/muuzaji/mipangilio': typeof MuuzajiMipangilioRoute
  '/admin': typeof AdminIndexRoute
  '/muuzaji': typeof MuuzajiIndexRoute
  '/admin/bidhaa/$id': typeof AdminBidhaaIdRouteWithChildren
  '/admin/bidhaa/ongeza': typeof AdminBidhaaOngezaRoute
  '/admin/zaidi/bajeti': typeof AdminZaidiBajetiRoute
  '/admin/zaidi/matumizi': typeof AdminZaidiMatumiziRoute
  '/admin/zaidi/store': typeof AdminZaidiStoreRoute
  '/admin/zaidi/wakala': typeof AdminZaidiWakalaRoute
  '/admin/zaidi/watumiaji': typeof AdminZaidiWatumiajiRoute
  '/admin/bidhaa': typeof AdminBidhaaIndexRoute
  '/admin/bidhaa/$id/Hariri': typeof AdminBidhaaIdHaririRoute
  '/admin/bidhaa/$id/Ongeza': typeof AdminBidhaaIdOngezaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/muuzaji': typeof MuuzajiRouteWithChildren
  '/admin/mauzo': typeof AdminMauzoRoute
  '/admin/ripoti': typeof AdminRipotiRoute
  '/admin/zaidi': typeof AdminZaidiRouteWithChildren
  '/muuzaji/mauzo': typeof MuuzajiMauzoRoute
  '/muuzaji/mipangilio': typeof MuuzajiMipangilioRoute
  '/admin/': typeof AdminIndexRoute
  '/muuzaji/': typeof MuuzajiIndexRoute
  '/admin/bidhaa/$id': typeof AdminBidhaaIdRouteWithChildren
  '/admin/bidhaa/ongeza': typeof AdminBidhaaOngezaRoute
  '/admin/zaidi/bajeti': typeof AdminZaidiBajetiRoute
  '/admin/zaidi/matumizi': typeof AdminZaidiMatumiziRoute
  '/admin/zaidi/store': typeof AdminZaidiStoreRoute
  '/admin/zaidi/wakala': typeof AdminZaidiWakalaRoute
  '/admin/zaidi/watumiaji': typeof AdminZaidiWatumiajiRoute
  '/admin/bidhaa/': typeof AdminBidhaaIndexRoute
  '/admin/bidhaa/$id/Hariri': typeof AdminBidhaaIdHaririRoute
  '/admin/bidhaa/$id/Ongeza': typeof AdminBidhaaIdOngezaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/muuzaji'
    | '/admin/mauzo'
    | '/admin/ripoti'
    | '/admin/zaidi'
    | '/muuzaji/mauzo'
    | '/muuzaji/mipangilio'
    | '/admin/'
    | '/muuzaji/'
    | '/admin/bidhaa/$id'
    | '/admin/bidhaa/ongeza'
    | '/admin/zaidi/bajeti'
    | '/admin/zaidi/matumizi'
    | '/admin/zaidi/store'
    | '/admin/zaidi/wakala'
    | '/admin/zaidi/watumiaji'
    | '/admin/bidhaa/'
    | '/admin/bidhaa/$id/Hariri'
    | '/admin/bidhaa/$id/Ongeza'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin/mauzo'
    | '/admin/ripoti'
    | '/admin/zaidi'
    | '/muuzaji/mauzo'
    | '/muuzaji/mipangilio'
    | '/admin'
    | '/muuzaji'
    | '/admin/bidhaa/$id'
    | '/admin/bidhaa/ongeza'
    | '/admin/zaidi/bajeti'
    | '/admin/zaidi/matumizi'
    | '/admin/zaidi/store'
    | '/admin/zaidi/wakala'
    | '/admin/zaidi/watumiaji'
    | '/admin/bidhaa'
    | '/admin/bidhaa/$id/Hariri'
    | '/admin/bidhaa/$id/Ongeza'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/muuzaji'
    | '/admin/mauzo'
    | '/admin/ripoti'
    | '/admin/zaidi'
    | '/muuzaji/mauzo'
    | '/muuzaji/mipangilio'
    | '/admin/'
    | '/muuzaji/'
    | '/admin/bidhaa/$id'
    | '/admin/bidhaa/ongeza'
    | '/admin/zaidi/bajeti'
    | '/admin/zaidi/matumizi'
    | '/admin/zaidi/store'
    | '/admin/zaidi/wakala'
    | '/admin/zaidi/watumiaji'
    | '/admin/bidhaa/'
    | '/admin/bidhaa/$id/Hariri'
    | '/admin/bidhaa/$id/Ongeza'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  MuuzajiRoute: typeof MuuzajiRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/muuzaji': {
      id: '/muuzaji'
      path: '/muuzaji'
      fullPath: '/muuzaji'
      preLoaderRoute: typeof MuuzajiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/mauzo': {
      id: '/admin/mauzo'
      path: '/mauzo'
      fullPath: '/admin/mauzo'
      preLoaderRoute: typeof AdminMauzoRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/ripoti': {
      id: '/admin/ripoti'
      path: '/ripoti'
      fullPath: '/admin/ripoti'
      preLoaderRoute: typeof AdminRipotiRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/zaidi': {
      id: '/admin/zaidi'
      path: '/zaidi'
      fullPath: '/admin/zaidi'
      preLoaderRoute: typeof AdminZaidiRouteImport
      parentRoute: typeof AdminRoute
    }
    '/muuzaji/': {
      id: '/muuzaji/'
      path: '/'
      fullPath: '/muuzaji/'
      preLoaderRoute: typeof MuuzajiIndexRouteImport
      parentRoute: typeof MuuzajiRoute
    }
    '/muuzaji/mauzo': {
      id: '/muuzaji/mauzo'
      path: '/mauzo'
      fullPath: '/muuzaji/mauzo'
      preLoaderRoute: typeof MuuzajiMauzoRouteImport
      parentRoute: typeof MuuzajiRoute
    }
    '/muuzaji/mipangilio': {
      id: '/muuzaji/mipangilio'
      path: '/mipangilio'
      fullPath: '/muuzaji/mipangilio'
      preLoaderRoute: typeof MuuzajiMipangilioRouteImport
      parentRoute: typeof MuuzajiRoute
    }
    '/admin/bidhaa/': {
      id: '/admin/bidhaa/'
      path: '/bidhaa'
      fullPath: '/admin/bidhaa/'
      preLoaderRoute: typeof AdminBidhaaIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/bidhaa/$id': {
      id: '/admin/bidhaa/$id'
      path: '/bidhaa/$id'
      fullPath: '/admin/bidhaa/$id'
      preLoaderRoute: typeof AdminBidhaaIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/bidhaa/ongeza': {
      id: '/admin/bidhaa/ongeza'
      path: '/bidhaa/ongeza'
      fullPath: '/admin/bidhaa/ongeza'
      preLoaderRoute: typeof AdminBidhaaOngezaRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/zaidi/bajeti': {
      id: '/admin/zaidi/bajeti'
      path: '/bajeti'
      fullPath: '/admin/zaidi/bajeti'
      preLoaderRoute: typeof AdminZaidiBajetiRouteImport
      parentRoute: typeof AdminZaidiRoute
    }
    '/admin/zaidi/matumizi': {
      id: '/admin/zaidi/matumizi'
      path: '/matumizi'
      fullPath: '/admin/zaidi/matumizi'
      preLoaderRoute: typeof AdminZaidiMatumiziRouteImport
      parentRoute: typeof AdminZaidiRoute
    }
    '/admin/zaidi/store': {
      id: '/admin/zaidi/store'
      path: '/store'
      fullPath: '/admin/zaidi/store'
      preLoaderRoute: typeof AdminZaidiStoreRouteImport
      parentRoute: typeof AdminZaidiRoute
    }
    '/admin/zaidi/wakala': {
      id: '/admin/zaidi/wakala'
      path: '/wakala'
      fullPath: '/admin/zaidi/wakala'
      preLoaderRoute: typeof AdminZaidiWakalaRouteImport
      parentRoute: typeof AdminZaidiRoute
    }
    '/admin/zaidi/watumiaji': {
      id: '/admin/zaidi/watumiaji'
      path: '/watumiaji'
      fullPath: '/admin/zaidi/watumiaji'
      preLoaderRoute: typeof AdminZaidiWatumiajiRouteImport
      parentRoute: typeof AdminZaidiRoute
    }
    '/admin/bidhaa/$id/Hariri': {
      id: '/admin/bidhaa/$id/Hariri'
      path: '/Hariri'
      fullPath: '/admin/bidhaa/$id/Hariri'
      preLoaderRoute: typeof AdminBidhaaIdHaririRouteImport
      parentRoute: typeof AdminBidhaaIdRoute
    }
    '/admin/bidhaa/$id/Ongeza': {
      id: '/admin/bidhaa/$id/Ongeza'
      path: '/Ongeza'
      fullPath: '/admin/bidhaa/$id/Ongeza'
      preLoaderRoute: typeof AdminBidhaaIdOngezaRouteImport
      parentRoute: typeof AdminBidhaaIdRoute
    }
  }
}

interface AdminZaidiRouteChildren {
  AdminZaidiBajetiRoute: typeof AdminZaidiBajetiRoute
  AdminZaidiMatumiziRoute: typeof AdminZaidiMatumiziRoute
  AdminZaidiStoreRoute: typeof AdminZaidiStoreRoute
  AdminZaidiWakalaRoute: typeof AdminZaidiWakalaRoute
  AdminZaidiWatumiajiRoute: typeof AdminZaidiWatumiajiRoute
}

const AdminZaidiRouteChildren: AdminZaidiRouteChildren = {
  AdminZaidiBajetiRoute: AdminZaidiBajetiRoute,
  AdminZaidiMatumiziRoute: AdminZaidiMatumiziRoute,
  AdminZaidiStoreRoute: AdminZaidiStoreRoute,
  AdminZaidiWakalaRoute: AdminZaidiWakalaRoute,
  AdminZaidiWatumiajiRoute: AdminZaidiWatumiajiRoute,
}

const AdminZaidiRouteWithChildren = AdminZaidiRoute._addFileChildren(
  AdminZaidiRouteChildren,
)

interface AdminBidhaaIdRouteChildren {
  AdminBidhaaIdHaririRoute: typeof AdminBidhaaIdHaririRoute
  AdminBidhaaIdOngezaRoute: typeof AdminBidhaaIdOngezaRoute
}

const AdminBidhaaIdRouteChildren: AdminBidhaaIdRouteChildren = {
  AdminBidhaaIdHaririRoute: AdminBidhaaIdHaririRoute,
  AdminBidhaaIdOngezaRoute: AdminBidhaaIdOngezaRoute,
}

const AdminBidhaaIdRouteWithChildren = AdminBidhaaIdRoute._addFileChildren(
  AdminBidhaaIdRouteChildren,
)

interface AdminRouteChildren {
  AdminMauzoRoute: typeof AdminMauzoRoute
  AdminRipotiRoute: typeof AdminRipotiRoute
  AdminZaidiRoute: typeof AdminZaidiRouteWithChildren
  AdminIndexRoute: typeof AdminIndexRoute
  AdminBidhaaIdRoute: typeof AdminBidhaaIdRouteWithChildren
  AdminBidhaaOngezaRoute: typeof AdminBidhaaOngezaRoute
  AdminBidhaaIndexRoute: typeof AdminBidhaaIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminMauzoRoute: AdminMauzoRoute,
  AdminRipotiRoute: AdminRipotiRoute,
  AdminZaidiRoute: AdminZaidiRouteWithChildren,
  AdminIndexRoute: AdminIndexRoute,
  AdminBidhaaIdRoute: AdminBidhaaIdRouteWithChildren,
  AdminBidhaaOngezaRoute: AdminBidhaaOngezaRoute,
  AdminBidhaaIndexRoute: AdminBidhaaIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface MuuzajiRouteChildren {
  MuuzajiMauzoRoute: typeof MuuzajiMauzoRoute
  MuuzajiMipangilioRoute: typeof MuuzajiMipangilioRoute
  MuuzajiIndexRoute: typeof MuuzajiIndexRoute
}

const MuuzajiRouteChildren: MuuzajiRouteChildren = {
  MuuzajiMauzoRoute: MuuzajiMauzoRoute,
  MuuzajiMipangilioRoute: MuuzajiMipangilioRoute,
  MuuzajiIndexRoute: MuuzajiIndexRoute,
}

const MuuzajiRouteWithChildren =
  MuuzajiRoute._addFileChildren(MuuzajiRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  MuuzajiRoute: MuuzajiRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
